### ISSUE TITLE
开抄

### ISSUE THREAD

**Issue by By-Ha** [AntiLeaf/SimpleDB#1]

**Comment by antileaf** [comment]
？:thinking:
没看懂您要表达什么

**Comment by By-Ha** [comment]
Ctrl c
Ctrl v

**Comment by antileaf** [comment]
🤔 如果您是在担心有人抄我的大作业，那大可不必，首先班里没有任何一个人认识我，其次即使被抄袭了跟我也没有关系，毕竟没有人要求必须 Private，而不能抄袭是明确的要求
